export const DEFAULT_CITY = 'durham';
export const DEFAULT_CITY_CENTER = { lat: 35.9940, lng: -78.8986 }; // Downtown Durham

// Simple ~10km city bounding box for filtering (rough dev bounds)
export const CITY_BOUNDS = {
  minLat: 35.93,
  maxLat: 36.06,
  minLng: -78.98,
  maxLng: -78.83,
};

// Durham recommended locations (seed data for dev)
export const DURHAM_RECS = [
  {
    id: 'durham-central-park',
    name: 'Durham Central Park',
    lat: 36.0032,
    lng: -78.9037,
    category: 'Park',
    landmarks: ['Main entrance', 'Playground', 'Pavilion'],
  },
  {
    id: 'american-tobacco-campus',
    name: 'American Tobacco Campus',
    lat: 35.9931,
    lng: -78.9040,
    category: 'Mixed-use / Hangout',
    landmarks: ['Lucky Strike Tower', 'Central courtyard', 'Water feature'],
  },
  {
    id: 'dbap',
    name: 'Durham Bulls Athletic Park',
    lat: 35.9916,
    lng: -78.9058,
    category: 'Stadium',
  },
  {
    id: 'duke-gardens',
    name: 'Sarah P. Duke Gardens',
    lat: 36.0003,
    lng: -78.9369,
    category: 'Garden',
    landmarks: ['Garden fountain', 'Terrace gardens entrance', 'Visitor center'],
  },
  {
    id: 'duke-chapel',
    name: 'Duke University Chapel',
    lat: 36.0019,
    lng: -78.9395,
    category: 'Sight',
  },
  {
    id: 'ninth-street',
    name: 'Ninth Street',
    lat: 36.0085,
    lng: -78.9255,
    category: 'Street / Cafés',
  },
  {
    id: 'fullsteam-brewery',
    name: 'Fullsteam Brewery',
    lat: 35.9945,
    lng: -78.8985,
    category: 'Brewery',
    landmarks: ['Bar area', 'Patio entrance', 'Front door'],
  },
  {
    id: 'motorco-music-hall',
    name: 'Motorco Music Hall',
    lat: 36.0025,
    lng: -78.9015,
    category: 'Music Venue',
  },
  {
    id: 'durham-food-hall',
    name: 'The Parlour Ice Cream',
    lat: 36.0089,
    lng: -78.9243,
    category: 'Dessert',
  },
  {
    id: 'cocoa-cinnamon',
    name: 'Cocoa Cinnamon',
    lat: 36.0087,
    lng: -78.9251,
    category: 'Café',
    landmarks: ['Espresso bar', 'Window seating', 'Front counter'],
  },
  {
    id: 'durham-farmers-market',
    name: "Durham Farmers' Market",
    lat: 36.0035,
    lng: -78.9041,
    category: 'Market',
  },
  {
    id: 'nasher-museum',
    name: 'Nasher Museum of Art',
    lat: 36.0023,
    lng: -78.9381,
    category: 'Museum',
  },
  {
    id: 'bennett-place',
    name: 'Bennett Place Historic Site',
    lat: 36.0452,
    lng: -78.9391,
    category: 'Historic Site',
  },
  {
    id: 'forest-hills-park',
    name: 'Forest Hills Park',
    lat: 36.0195,
    lng: -78.9445,
    category: 'Park',
  },
  {
    id: 'durham-athletic-park',
    name: 'Durham Athletic Park',
    lat: 35.9952,
    lng: -78.9072,
    category: 'Park',
  },
  {
    id: 'west-point-on-the-eno',
    name: 'West Point on the Eno',
    lat: 36.0621,
    lng: -78.9248,
    category: 'Park',
  },
  {
    id: 'brightleaf-square',
    name: 'Brightleaf Square',
    lat: 35.9944,
    lng: -78.9023,
    category: 'Shopping',
  },
  {
    id: 'rue-cler',
    name: 'Rue Cler',
    lat: 36.0091,
    lng: -78.9249,
    category: 'French Café',
  },
  {
    id: 'ponysaurus-brewing',
    name: 'Ponysaurus Brewing',
    lat: 36.0026,
    lng: -78.9018,
    category: 'Brewery',
  },
  {
    id: 'comics-games',
    name: 'Atomic Empire',
    lat: 35.9748,
    lng: -78.8852,
    category: 'Games & Comics',
  },
  {
    id: 'eno-river-state-park',
    name: 'Eno River State Park',
    lat: 36.0789,
    lng: -78.9455,
    category: 'Nature Park',
  },
];
